// File generated by FlutterFire CLI — secrets moved to --dart-define
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  // ── compile-time secrets (injected via --dart-define) ──────────────────────
  static const _apiKeyWeb      = String.fromEnvironment('FIREBASE_API_KEY_WEB');
  static const _apiKeyAndroid  = String.fromEnvironment('FIREBASE_API_KEY_ANDROID');
  static const _apiKeyIos      = String.fromEnvironment('FIREBASE_API_KEY_IOS');
  static const _appIdAndroid   = String.fromEnvironment('FIREBASE_APP_ID_ANDROID');
  static const _appIdIos       = String.fromEnvironment('FIREBASE_APP_ID_IOS');
  static const _appIdWeb       = String.fromEnvironment('FIREBASE_APP_ID_WEB');
  static const _appIdWindows   = String.fromEnvironment('FIREBASE_APP_ID_WINDOWS');
  static const _senderId       = String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID');
  static const _projectId      = String.fromEnvironment('FIREBASE_PROJECT_ID');
  static const _storageBucket  = String.fromEnvironment('FIREBASE_STORAGE_BUCKET');
  static const _authDomain     = String.fromEnvironment('FIREBASE_AUTH_DOMAIN');
  static const _iosBundleId    = String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS:     return ios;
      case TargetPlatform.macOS:   return macos;
      case TargetPlatform.windows: return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            _apiKeyWeb,
    appId:             _appIdWeb,
    messagingSenderId: _senderId,
    projectId:         _projectId,
    authDomain:        _authDomain,
    storageBucket:     _storageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            _apiKeyAndroid,
    appId:             _appIdAndroid,
    messagingSenderId: _senderId,
    projectId:         _projectId,
    storageBucket:     _storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            _apiKeyIos,
    appId:             _appIdIos,
    messagingSenderId: _senderId,
    projectId:         _projectId,
    storageBucket:     _storageBucket,
    iosBundleId:       _iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:            _apiKeyIos,
    appId:             _appIdIos,
    messagingSenderId: _senderId,
    projectId:         _projectId,
    storageBucket:     _storageBucket,
    iosBundleId:       _iosBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:            _apiKeyWeb,
    appId:             _appIdWindows,
    messagingSenderId: _senderId,
    projectId:         _projectId,
    authDomain:        _authDomain,
    storageBucket:     _storageBucket,
  );
}